pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Étape pour récupérer le code depuis un système de contrôle de version (par exemple, Git)
                git 'git@github.com:hardvaark/shopjenkins.git'
            }
        }

        stage('Build') {
            steps {
                // Étape pour compiler le code et générer le fichier JAR avec Maven
                sh 'mvn clean install'
            }
        }

        stage('Test') {
            steps {
                // Étape pour exécuter les tests unitaires avec Maven
                sh 'mvn test'
            }
        }

        stage('Deploy') {
            steps {
                // Étape pour déployer le fichier JAR sur le serveur
                // Vous pouvez modifier cette étape en fonction de votre environnement de déploiement
                // sh 'scp target/myapp.jar user@server:/path/to/deploy'
                echo 'En attente de déploiement ...'
            }
        }
    }

    post {
        success {
            // Étape exécutée si le pipeline réussit
            echo 'Le pipeline a réussi! Félicitations!'
        }
        failure {
            // Étape exécutée si le pipeline échoue
            echo 'Le pipeline a échoué. Veuillez vérifier les étapes précédentes.'
        }
    }
}

